# Generated by Django 4.2 on 2025-08-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'location'], name='jobs_job_title_0bda61_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'job_type'], name='jobs_job_categor_675160_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'date_posted'], name='jobs_job_is_acti_21202a_idx'),
        ),
    ]
